### ISSUE TITLE
Legend titles

### ISSUE THREAD

**Issue by vermeulendivan** [kartoza/least-cost-electrification-somaliland#12]
Legend title/heading for many cases does not display ideally. For instance, "somaliland_nighttime_lights_2020"  should rather be changeable to "Somaliland nighttime lights 2020". Example legend shown:
![image](https://user-images.githubusercontent.com/79740955/140302165-238bae79-3fc9-413a-a749-34d5d565a6ed.png)
Adding a title to the style does not make a difference. Best will be to make use of the title, which can be set for all legends in this manner, to be used as the legend heading.
![image](https://user-images.githubusercontent.com/79740955/140302360-f1e7fd57-1d94-436e-8940-887c523cc0e5.png)
Admire stated that it will be best to a model so that this can be customisable in the admin interface.

**Comment by meomancer** [comment]
hi @NyakudyaA 
the legend is coming from geoserver directly, so the text should be managed by geoserver
not sure why we need to add it on django admin because it will make double maintenance (if we change title geoserver style, we need to change it on django as well)
should we fix it in geoserver rather than creating in admin?

**Comment by meomancer** [comment]
hi @vermeulendivan and @NyakudyaA 
Geonode already have model for that
you can check it in here

https://somaliland.gep.kartoza.com/en/admin/layers/style/

Just change the sld title manually

Note:
i already fixed this layer legend title

**Comment by vermeulendivan** [comment]
Legend titles has been updated to make use of more descriptive wording and legend entry naming has also been improved.
