### ISSUE TITLE
Duplicate legends for map layers

### ISSUE THREAD

**Issue by vermeulendivan** [kartoza/least-cost-electrification-somaliland#13]
Two legends are shown for the 'Small scale hydrological power' map layer. Only one should be shown, and a legend request only shows one legend:
![image](https://user-images.githubusercontent.com/79740955/141783819-f2d7cac1-10a7-4b9f-8dba-e37d736dc362.png)

The same happens with the 'OSM Roads' map layer. There is 4 legends, the other legends are not visible due to a large number of legend entries
![image](https://user-images.githubusercontent.com/79740955/141784101-7a92a91f-cf2a-45a8-abac-a30858877c7a.png)

**Comment by lkwalke4** [comment]
@meomancer could you please glance at this issue too? Don't spend too much time, but if you could glance at it I would appreciate it!

**Comment by meomancer** [comment]
hi @vermeulendivan @lkwalke4 
the Small Scale Hydrology has been fixed

Here how to fix it

go to https://somaliland.gep.kartoza.com/en/admin/base/link/
and filter by the layer name

After that we can see on the column name "Legend"
Those line are used for rendering legend
![Selection_306](https://user-images.githubusercontent.com/4530905/142553861-b616bffb-b1d4-4b2e-b1cb-acf3be29ae9a.png)

I haven't fixed the OSM Roads, because the legend is different

Link:
https://somaliland.gep.kartoza.com/en/admin/base/link/?o=-5&q=OSM+Road
There are 4 legend
![Selection_307](https://user-images.githubusercontent.com/4530905/142553994-a7c70980-43a8-40e5-9ad7-190c3bf1347d.png)

But there are different style for the legend
3 of it using 
https://somaliland.gep.kartoza.com/geoserver/ows?service=WMS&request=GetLegendGraphic&format=image/png&WIDTH=20&HEIGHT=20&LAYER=geonode:somaliland_osm_roads&STYLE=somaliland_osm_roads&legend_options=fontAntiAliasing:true;fontSize:12;forceLabels:on
![Selection_308](https://user-images.githubusercontent.com/4530905/142554036-386a2f29-fac5-428b-b458-9ac2b97d3809.png)

and 1 of it using
https://somaliland.gep.kartoza.com/geoserver/ows?service=WMS&request=GetLegendGraphic&format=image/png&WIDTH=20&HEIGHT=20&LAYER=geonode:somaliland_osm_roads&STYLE=roads_admire&legend_options=fontAntiAliasing:true;fontSize:12;forceLabels:on

not sure which one should we use

could you help me fix it @vermeulendivan 
just delete the legend that we don't need

**Comment by vermeulendivan** [comment]
@meomancer I have deleted the no longer required style from the styles in the geoserver. Anywhere else I need to make changes?

**Comment by vermeulendivan** [comment]
![image](https://user-images.githubusercontent.com/79740955/142611097-4a4e28ac-80a9-468b-9ad3-f5165601b160.png)

**Comment by vermeulendivan** [comment]
@lkwalke4 both of these tasks has been fixed. The osm roads only now displays as in the above example. The symbology I'm using is the same as Abi used for kenya osm roads. It looks too black, but when zooming in it looks much better. This is due to the large number of unclassified roads - how we received the data.

**Comment by meomancer** [comment]
Could we close this @vermeulendivan @lkwalke4 ?
I think the original problem has been fixed?

**Comment by vermeulendivan** [comment]
@meomancer @lkwalke4 Yes, this issue has been resolved.
