### ISSUE TITLE
SEP Modeling Styling

### ISSUE THREAD

**Issue by lkwalke4** [kartoza/least-cost-electrification-somaliland#18]
Hi Admire and Irwan,

Things are looking good in the SEP. However, there is an issue with how we're styling the modeling results. From a small scale, the results look good. However, can we make the results more transparent or switch to just an outline (as opposed to solid fill) as the user zooms in? Please see below. When you zoom in, you really can't make anything out on the underlying basemap.

Any ideas on how to style it so that you can see things under the modeling layers when zoomed in?

![image](https://user-images.githubusercontent.com/18428984/141844778-14f445ee-704a-47b3-86d2-ae65b80766d7.png)

![image](https://user-images.githubusercontent.com/18428984/141844809-3afe113f-e8a6-4b23-b99e-221db801a117.png)

**Comment by NyakudyaA** [comment]
@lkwalke4 we can implement clustering if it helps

**Comment by lkwalke4** [comment]
@NyakudyaA whatever you think might be best. @timlinux had suggested an easy fix might also be to just use the satellite imagery as the basemap. What do you think about that?

![image](https://user-images.githubusercontent.com/18428984/141845686-e1d6cb31-b7dc-4ad0-a017-6741f1c16e88.png)

**Comment by meomancer** [comment]
hi @lkwalke4 @NyakudyaA @timlinux 

so the problem is this, isn't it?
> Any ideas on how to style it so that you can see things under the modeling layers when zoomed in?

The styling is not coming from geoserver, but it is from frontend. The style is based on technology, so we can't change the color or the style.

> @lkwalke4 we can implement clustering if it helps

i think we can't implement clustering because the data needs to be per geometry (because user needs actual data using ID of the geomerty). And also we still can't see the things under it.

> However, can we make the results more transparent or switch to just an outline (as opposed to solid fill) as the user zooms in?

we can't switch using just outline because the color is needed for knowing the technology of the cluster.

>  @timlinux had suggested an easy fix might also be to just use the satellite imagery as the basemap.

and also for changing basemap to satellite, we still can't see what under the cluster model, isn't it? because the cluster is the most top of the all layers.

for me i think we can do is creating opacity control? 
so user can change the opacity by themself to see basemap under it?
we can also create this control for all layer (as well as overlay layer) so user can control the look on the map

what do you think?
if creating the control, i need like 4 hours for it

**Comment by lkwalke4** [comment]
@meomancer I think that opacity control is worth it, if it can be done within 4 hours. Please proceed.

**Comment by meomancer** [comment]
this is deployed @lkwalke4 
please check it and do hard refresh

**Comment by lkwalke4** [comment]
Thank you so much @meomancer, it looks great!
